In [ ]:
import importlib
importlib.reload(importlib.import_module('esmDMS'))  # Replace 'esmDMS

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Testing

from esmDMS import CellularDMSInput, ViralDMSInput, esmDMS, ESMDMSConfig
# Example usage

embedding_models = ['esm2_t6_8M_UR50D', 'esm2_t12_35M_UR50D', 
                    'esm2_t30_150M_UR50D', 'esm2_t33_650M_UR50D', 
                    'esm2_t36_3B_UR50D']

embedding_methods = ['per_residue', 'mean_pooling', 'cls_token']


TpoRINPUT = CellularDMSInput(
    reference_nuc_path='/Users/dylanwells/popDMS/dylan_refactor/data/raw_data/TpoR_reference_sequence.dat',
    mavedb_csv_path='/Users/dylanwells/popDMS/dylan_refactor/data/raw_data/TpoR_nucleotide_counts.csv'
)

BF520INPUT = ViralDMSInput(
    pre_files = ("/Users/dylanwells/popDMS/dylan_refactor/data/raw_data/BF520_mutDNA-1_codoncounts.csv",
                "/Users/dylanwells/popDMS/dylan_refactor/data/raw_data/BF520_mutDNA-2_codoncounts.csv",
                "/Users/dylanwells/popDMS/dylan_refactor/data/raw_data/BF520_mutDNA-3_codoncounts.csv"),
    post_files = ("/Users/dylanwells/popDMS/dylan_refactor/data/raw_data/BF520_mutvirus-1_codoncounts.csv",
                 "/Users/dylanwells/popDMS/dylan_refactor/data/raw_data/BF520_mutvirus-2_codoncounts.csv",
                 "/Users/dylanwells/popDMS/dylan_refactor/data/raw_data/BF520_mutvirus-3_codoncounts.csv")
)


ESMCONFIG = ESMDMSConfig(
    embedding_model='esm2_t6_8M_UR50D',
    embedding_method='per_residue'
)

In [4]:
test_cellular_dms = esmDMS(input_data=TpoRINPUT, config=ESMCONFIG)

In [5]:

test_cellular_dms.process_raw_data()

In [6]:
test_cellular_dms.sequence_dataframe.head()

   SequenceIndex  Replicate  Generation  Frequency
0              0          1           0        121
1              0          1           1        247
2              0          2           0        121
3              0          2           1        129
4              0          3           0        121

In [7]:
test_cellular_dms.sequence_to_mutation_sites

{0: [30],
 1: [30],
 2: [30],
 3: [30],
 4: [30],
 5: [30],
 6: [29],
 7: [2],
 8: [2],
 9: [2, 28],
 10: [2, 18],
 11: [2],
 12: [2, 28],
 13: [2],
 14: [2],
 15: [2, 28],
 16: [2],
 17: [2, 28],
 18: [2, 28],
 19: [2, 28],
 20: [2, 28],
 21: [2, 18],
 22: [2, 15],
 23: [2, 9],
 24: [29],
 25: [29],
 26: [29],
 27: [29],
 28: [29],
 29: [29],
 30: [29],
 31: [29],
 32: [29],
 33: [29],
 34: [29],
 35: [29],
 36: [29],
 37: [29],
 38: [29],
 39: [29],
 40: [29],
 41: [29],
 42: [28],
 43: [28],
 44: [28, 30],
 45: [28, 29],
 46: [28, 29],
 47: [28],
 48: [28, 30],
 49: [28, 30],
 50: [28],
 51: [28, 30],
 52: [28, 29],
 53: [28],
 54: [28],
 55: [28],
 56: [28],
 57: [28],
 58: [28, 30],
 59: [28, 29],
 60: [28],
 61: [28],
 62: [28],
 63: [28, 30],
 64: [28],
 65: [28],
 66: [28],
 67: [28, 30],
 68: [28, 29],
 69: [28],
 70: [28, 30],
 71: [28, 30],
 72: [28],
 73: [28],
 74: [28],
 75: [27, 28],
 76: [27],
 77: [27],
 78: [27],
 79: [27],
 80: [2],
 81: [2, 18],
 82: [2, 28],
 83: [2],
 84: [2],
 85: [2],
 86: [2],
 87: [2],
 88: [2],
 89: [2],
 90: [2],
 91: [2, 18],
 92: [2],
 93: [2, 28],
 94: [2, 28],
 95: [2, 28],
 96: [2, 28],
 97: [2, 18],
 98: [2, 15],
 99: [2, 14],
 100: [2, 7],
 101: [2, 6],
 102: [2],
 103: [2],
 104: [26],
 105: [26],
 106: [26],
 107: [26],
 108: [26],
 109: [26],
 110: [26],
 111: [26],
 112: [26],
 113: [26],
 114: [26],
 115: [26, 28],
 116: [26, 28],
 117: [26],
 118: [26],
 119: [26],
 120: [26],
 121: [26],
 122: [25, 28],
 123: [25, 28],
 124: [25],
 125: [25, 28],
 126: [25],
 127: [25],
 128: [25, 28],
 129: [25],
 130: [25],
 131: [25],
 132: [25],
 133: [25],
 134: [25],
 135: [25, 28],
 136: [25],
 137: [25],
 138: [25],
 139: [25],
 140: [25],
 141: [25],
 142: [25, 28],
 143: [25],
 144: [25],
 145: [25],
 146: [25],
 147: [24],
 148: [24, 28],
 149: [24],
 150: [24],
 151: [24, 28],
 152: [24, 28],
 153: [24],
 154: [24],
 155: [24],
 156: [24],
 157: [24],
 158: [24],
 159: [24],
 160: [24, 28],
 161: [24],
 162: [24],
 163: [24],
 164: [24],
 165: [23],
 166: [23],
 167: [23],
 168: [23],
 169: [23],
 170: [23],
 171: [23, 28],
 172: [23, 28],
 173: [23],
 174: [23],
 175: [23],
 176: [23],
 177: [23],
 178: [1, 28],
 179: [1, 28],
 180: [1, 28],
 181: [1, 18],
 182: [1, 18],
 183: [1, 6],
 184: [1],
 185: [22],
 186: [22, 28],
 187: [22, 28],
 188: [22],
 189: [22],
 190: [22, 28],
 191: [22],
 192: [22],
 193: [22],
 194: [22],
 195: [22],
 196: [22],
 197: [22, 28],
 198: [22, 28],
 199: [22],
 200: [22],
 201: [22],
 202: [22],
 203: [22, 28],
 204: [22],
 205: [22],
 206: [22, 28],
 207: [22],
 208: [22],
 209: [22],
 210: [22, 28],
 211: [22],
 212: [21],
 213: [21],
 214: [21],
 215: [21, 28],
 216: [21, 28],
 217: [21, 28],
 218: [21],
 219: [21],
 220: [21],
 221: [21],
 222: [21],
 223: [21],
 224: [21],
 225: [21],
 226: [21],
 227: [27],
 228: [27],
 229: [27],
 230: [27, 28],
 231: [27],
 232: [27],
 233: [27],
 234: [27],
 235: [27],
 236: [27],
 237: [27],
 238: [27],
 239: [27],
 240: [27],
 241: [27],
 242: [27],
 243: [26, 28],
 244: [26, 28],
 245: [26, 28],
 246: [26, 28],
 247: [26],
 248: [26],
 249: [26, 28],
 250: [26, 28],
 251: [26],
 252: [2],
 253: [21],
 254: [21],
 255: [21],
 256: [21, 28],
 257: [21],
 258: [21],
 259: [21],
 260: [21],
 261: [20, 28],
 262: [20, 28],
 263: [20, 28],
 264: [20],
 265: [20, 28],
 266: [20],
 267: [20],
 268: [20, 28],
 269: [20, 28],
 270: [20],
 271: [20],
 272: [20],
 273: [20],
 274: [20, 28],
 275: [20],
 276: [20],
 277: [20],
 278: [20],
 279: [20, 28],
 280: [20, 28],
 281: [19],
 282: [19],
 283: [19],
 284: [19],
 285: [19],
 286: [19, 28],
 287: [19],
 288: [19, 27],
 289: [19],
 290: [19],
 291: [19],
 292: [19],
 293: [19],
 294: [18, 28],
 295: [18],
 296: [18, 28],
 297: [18, 28],
 298: [18, 28],
 299: [18, 28],
 300: [18, 28],
 301: [18, 28],
 302: [18, 21],
 303: [18, 20],
 304: [18],
 305: [18, 28],
 306: [18, 28],
 307: [18, 19],
 308: [18],
 309: [18, 28],
 310: [18, 28],
 311: [18, 28],
 312: [18, 20],
 313: [18],
 314: [18, 28],
 315: [18],
 316: [18, 29],
 317: [18, 29],
 318: [18, 29],
 319: [18, 29],
 320: [18, 29],
 321: [18, 29],
 322: [18, 29],
 323: [18, 29],
 324: [18, 28],
 325: [18, 28],
 326: [18, 28],
 327: [18, 28],
 328: [18, 28],
 329: [18, 28],
 330: [18, 28],
 331: [18, 28],
 332: [18, 28],
 333: [18, 28],
 334: [18, 27],
 335: [18, 27],
 336: [18, 27],
 337: [18, 27],
 338: [18, 27],
 339: [18, 27],
 340: [18, 27],
 341: [18, 26],
 342: [18, 26],
 343: [18, 26],
 344: [18, 26],
 345: [18, 26],
 346: [18, 26],
 347: [18, 25],
 348: [18, 25],
 349: [18, 25],
 350: [18, 25],
 351: [18, 25],
 352: [18, 24],
 353: [18, 24],
 354: [18, 24],
 355: [18, 23],
 356: [18, 23],
 357: [18, 22],
 358: [18, 22],
 359: [18, 21],
 360: [18, 21],
 361: [18, 21],
 362: [18, 21],
 363: [18, 20],
 364: [18, 20],
 365: [18, 20],
 366: [18, 20],
 367: [18, 20],
 368: [18, 20],
 369: [18, 20],
 370: [18, 20],
 371: [18, 19],
 372: [18, 19],
 373: [18, 19],
 374: [24],
 375: [24],
 376: [24],
 377: [24],
 378: [24],
 379: [23, 28],
 380: [23],
 381: [23],
 382: [23, 28],
 383: [23],
 384: [23],
 385: [23],
 386: [23],
 387: [23],
 388: [23, 28],
 389: [23],
 390: [23, 28],
 391: [18, 19],
 392: [18, 19],
 393: [18, 19],
 394: [18, 19],
 395: [18, 19],
 396: [18, 19],
 397: [18, 19],
 398: [18, 19],
 399: [18, 19],
 400: [18, 30],
 401: [18, 26],
 402: [18, 25],
 403: [18, 23],
 404: [18, 22],
 405: [18],
 406: [18],
 407: [18],
 408: [18],
 409: [18],
 410: [18],
 411: [18],
 412: [18, 28],
 413: [18],
 414: [18],
 415: [18],
 416: [18],
 417: [18],
 418: [18],
 419: [1],
 420: [1],
 421: [1],
 422: [1],
 423: [1],
 424: [1, 18],
 425: [1],
 426: [1],
 427: [16],
 428: [16, 18],
 429: [16],
 430: [16, 18],
 431: [16],
 432: [16, 18],
 433: [16],
 434: [16],
 435: [16, 28],
 436: [16, 18],
 437: [16],
 438: [16],
 439: [16],
 440: [16],
 441: [16, 28],
 442: [16, 18],
 443: [16],
 444: [16],
 445: [16, 28],
 446: [16],
 447: [16],
 448: [16],
 449: [16],
 450: [16, 28],
 451: [15, 28],
 452: [15, 28],
 453: [15, 28],
 454: [15, 18],
 455: [15],
 456: [15, 28],
 457: [15],
 458: [15, 18],
 459: [15],
 460: [15, 28],
 461: [15, 18],
 462: [15],
 463: [15],
 464: [15],
 465: [15, 23],
 466: [15, 18],
 467: [15, 18],
 468: [15],
 469: [15, 18],
 470: [15],
 471: [15],
 472: [15, 28],
 473: [15, 28],
 474: [15, 18],
 475: [15],
 476: [15, 18],
 477: [15],
 478: [15],
 479: [15],
 480: [15],
 481: [15],
 482: [20],
 483: [20],
 484: [20],
 485: [20],
 486: [20],
 487: [20],
 488: [20, 28],
 489: [20],
 490: [20],
 491: [1, 28],
 492: [1],
 493: [1, 18],
 494: [1, 14],
 495: [1, 28],
 496: [1, 28],
 497: [1],
 498: [1, 18],
 499: [1, 14],
 500: [1, 28],
 501: [1, 28],
 502: [1, 28],
 503: [1, 28],
 504: [1],
 505: [1, 18],
 506: [19, 28],
 507: [19],
 508: [19],
 509: [19],
 510: [19, 28],
 511: [19, 28],
 512: [19],
 513: [19],
 514: [19],
 515: [19, 28],
 516: [19],
 517: [19],
 518: [19, 28],
 519: [15, 28],
 520: [15, 28],
 521: [15, 28],
 522: [15, 28],
 523: [15, 28],
 524: [15, 23],
 525: [15, 18],
 526: [15],
 527: [15],
 528: [15, 18],
 529: [15],
 530: [15, 28],
 531: [15],
 532: [14, 28],
 533: [14, 28],
 534: [14, 28],
 535: [14, 28],
 536: [14, 18],
 537: [14, 18],
 538: [14, 15],
 539: [14],
 540: [14, 28],
 541: [14, 28],
 542: [14, 28],
 543: [14, 15],
 544: [14],
 545: [14, 28],
 546: [14, 28],
 547: [14, 28],
 548: [14, 28],
 549: [14, 28],
 550: [14, 28],
 551: [14, 25],
 552: [14, 18],
 553: [14, 18],
 554: [14, 15],
 555: [14],
 556: [14],
 557: [14],
 558: [14, 28],
 559: [14],
 560: [14],
 561: [14],
 562: [14],
 563: [13],
 564: [13, 28],
 565: [13, 28],
 566: [13, 18],
 567: [13],
 568: [13],
 569: [13, 18],
 570: [13],
 571: [13],
 572: [13],
 573: [13],
 574: [13],
 575: [13],
 576: [13],
 577: [13],
 578: [13],
 579: [13],
 580: [13],
 581: [13],
 582: [13],
 583: [13],
 584: [13, 28],
 585: [13, 18],
 586: [13],
 587: [13],
 588: [12, 28],
 589: [12, 28],
 590: [12, 18],
 591: [12, 14, 18],
 592: [12, 13],
 593: [12],
 594: [12, 28],
 595: [12, 28],
 596: [12, 18],
 597: [12],
 598: [12, 28],
 599: [12, 18],
 600: [12],
 601: [12, 28],
 602: [12, 28],
 603: [12, 18],
 604: [12],
 605: [12, 18],
 606: [12],
 607: [12],
 608: [12, 28],
 609: [12],
 610: [12],
 611: [12, 28],
 612: [12],
 613: [12],
 614: [12],
 615: [12],
 616: [12, 28],
 617: [12, 28],
 618: [12, 18],
 619: [12],
 620: [12],
 621: [12],
 622: [18],
 623: [18, 28],
 624: [17, 18],
 625: [17],
 626: [17],
 627: [17, 28],
 628: [17, 18],
 629: [17],
 630: [17],
 631: [17],
 632: [17],
 633: [17],
 634: [17, 28],
 635: [17, 28],
 636: [17, 18],
 637: [17],
 638: [17, 18],
 639: [17],
 640: [17, 28],
 641: [17, 18],
 642: [17],
 643: [17],
 644: [17],
 645: [17],
 646: [17],
 647: [17],
 648: [17],
 649: [17],
 650: [17, 28],
 651: [17, 28],
 652: [17, 28],
 653: [17, 18],
 654: [17],
 655: [17, 18],
 656: [17],
 657: [16, 28],
 658: [16, 28],
 659: [16, 28],
 660: [16, 18],
 661: [16],
 662: [16, 28],
 663: [16],
 664: [16],
 665: [16],
 666: [1],
 667: [1],
 668: [1],
 669: [1],
 670: [1, 18],
 671: [1],
 672: [1],
 673: [1],
 674: [1],
 675: [12],
 676: [12],
 677: [12],
 678: [12, 28],
 679: [12, 28],
 680: [12, 28],
 681: [12, 18],
 682: [12],
 683: [11, 28],
 684: [11],
 685: [11, 28],
 686: [11, 18],
 687: [11],
 688: [11],
 689: [11, 28],
 690: [11, 28],
 691: [11, 28],
 692: [11],
 693: [11],
 694: [11, 28],
 695: [11, 18],
 696: [11],
 697: [11],
 698: [11],
 699: [11],
 700: [11, 28],
 701: [11, 28],
 702: [11, 28],
 703: [11],
 704: [11, 28],
 705: [11, 18],
 706: [11],
 707: [11],
 708: [11],
 709: [9],
 710: [9],
 711: [9, 18],
 712: [9],
 713: [9, 28],
 714: [9],
 715: [9, 28],
 716: [9, 28],
 717: [9, 28],
 718: [9, 28],
 719: [9, 28],
 720: [9, 28],
 721: [9, 18],
 722: [9, 11],
 723: [9],
 724: [9, 18],
 725: [9],
 726: [9],
 727: [9],
 728: [9],
 729: [8, 28],
 730: [8, 28],
 731: [8, 28],
 732: [8, 28],
 733: [8],
 734: [8, 28],
 735: [8, 18],
 736: [8],
 737: [8, 28],
 738: [8, 28],
 739: [8, 28],
 740: [8, 28],
 741: [8, 18],
 742: [8, 14],
 743: [8],
 744: [8],
 745: [8],
 746: [8],
 747: [8],
 748: [8],
 749: [8, 28],
 750: [8, 28],
 751: [8, 28],
 752: [8, 28],
 753: [8, 28],
 754: [8, 18],
 755: [8],
 756: [8],
 757: [8],
 758: [8, 14],
 759: [8],
 760: [8],
 761: [8],
 762: [8],
 763: [8, 28],
 764: [8, 18],
 765: [8],
 766: [8],
 767: [8],
 768: [8],
 769: [7, 28],
 770: [7, 28],
 771: [7, 28],
 772: [7, 18],
 773: [7],
 774: [7, 28],
 775: [7, 28],
 776: [7, 28],
 777: [7, 18],
 778: [7],
 779: [7],
 780: [7, 28],
 781: [14, 30],
 782: [14, 28],
 783: [14, 28],
 784: [14, 26],
 785: [14, 25],
 786: [14, 22],
 787: [14, 20],
 788: [14, 20],
 789: [14, 18],
 790: [14],
 791: [14],
 792: [14, 28],
 793: [14, 28],
 794: [14, 18],
 795: [14],
 796: [14],
 797: [14],
 798: [14, 28],
 799: [14, 28],
 800: [14],
 801: [14],
 802: [14, 28],
 803: [14],
 804: [14],
 805: [14],
 806: [7],
 807: [7],
 808: [7, 28],
 809: [7, 28],
 810: [7],
 811: [7, 28],
 812: [7, 18],
 813: [7],
 814: [7],
 815: [7],
 816: [7, 28],
 817: [7],
 818: [7],
 819: [7],
 820: [7, 28],
 821: [7],
 822: [7],
 823: [7],
 824: [7, 28],
 825: [7, 28],
 826: [7, 28],
 827: [7],
 828: [7],
 829: [7],
 830: [7],
 831: [6, 28],
 832: [0, 11],
 833: [0, 9],
 834: [0],
 835: [6],
 836: [6],
 837: [6],
 838: [6],
 839: [6],
 840: [6, 28],
 841: [6, 28],
 842: [6, 18],
 843: [6],
 844: [6, 28],
 845: [6],
 846: [6],
 847: [6],
 848: [6],
 849: [6],
 850: [6],
 851: [6],
 852: [6, 28],
 853: [6],
 854: [6],
 855: [5, 28],
 856: [5, 28],
 857: [5, 18],
 858: [5],
 859: [5, 28],
 860: [5, 28],
 861: [5, 28],
 862: [5, 28],
 863: [5, 28],
 864: [5, 18],
 865: [5, 18],
 866: [5],
 867: [5],
 868: [5],
 869: [5],
 870: [5, 28],
 871: [5, 18],
 872: [5, 15],
 873: [5],
 874: [5],
 875: [5],
 876: [5, 28],
 877: [5, 18],
 878: [5],
 879: [5],
 880: [5],
 881: [5, 28],
 882: [5],
 883: [5],
 884: [5],
 885: [5],
 886: [5],
 887: [5],
 888: [5, 28],
 889: [5, 28],
 890: [5, 28],
 891: [5, 28],
 892: [5, 18],
 893: [5, 15],
 894: [5, 14],
 895: [5],
 896: [5],
 897: [4, 28],
 898: [4, 28],
 899: [11],
 900: [11],
 901: [11, 28],
 902: [11, 28],
 903: [11, 28],
 904: [11, 18],
 905: [11],
 906: [11],
 907: [11, 18],
 908: [11],
 909: [11],
 910: [10, 28],
 911: [10],
 912: [10, 28],
 913: [10, 28],
 914: [10, 18],
 915: [10],
 916: [10, 18],
 917: [10],
 918: [10, 28],
 919: [10, 28],
 920: [10, 18],
 921: [10],
 922: [10],
 923: [10],
 924: [10, 28],
 925: [10, 28],
 926: [10, 28],
 927: [10, 28],
 928: [10, 28],
 929: [10, 14],
 930: [10],
 931: [10],
 932: [10],
 933: [10],
 934: [10, 28],
 935: [10, 28],
 936: [10],
 937: [10],
 938: [10],
 939: [10],
 940: [10, 28],
 941: [10, 18],
 942: [10],
 943: [10],
 944: [10],
 945: [10],
 946: [10],
 947: [0, 28],
 948: [0, 18],
 949: [0],
 950: [0],
 951: [0, 28],
 952: [0, 28],
 953: [0, 28],
 954: [0, 28],
 955: [0, 18],
 956: [0, 15],
 957: [0, 14],
 958: [0],
 959: [9],
 960: [9, 28],
 961: [9, 28],
 962: [9],
 963: [9, 18],
 964: [9],
 965: [9],
 966: [9, 28],
 967: [9, 28],
 968: [9, 28],
 969: [9, 28],
 970: [9, 18],
 971: [9, 14],
 972: [9, 14],
 973: [9, 11],
 974: [9],
 975: [9],
 976: [9],
 977: [9, 28],
 978: [9, 28],
 979: [9, 28],
 980: [9],
 981: [9],
 982: [9, 28],
 983: [9],
 984: [4],
 985: [4, 14],
 986: [4, 28],
 987: [4],
 988: [4, 28],
 989: [4],
 990: [4, 28],
 991: [4, 28],
 992: [4, 18],
 993: [4],
 994: [4],
 995: [4],
 996: [4, 28],
 997: [4, 28],
 998: [4, 18],
 999: [4],
 ...}

In [8]:
len(test_cellular_dms.sequence_to_protein_sequence)

1079

In [9]:
test_viral_dms = esmDMS(input_data=BF520INPUT, config=ESMCONFIG)

In [10]:
test_viral_dms.process_raw_data()

In [11]:
test_viral_dms.sequence_dataframe.head()

   SequenceIndex  Replicate  Generation  Frequency
0              0          1           0          0
1              0          1           1          0
2              0          2           0          0
3              0          2           1          0
4              0          3           0          0

In [12]:
# Create a test dictionary and then save it to disk as a .npy file
test_dict = {'a': 1, 'b': 2, 'c': 3}
np.save('/Users/dylanwells/popDMS/dylan_refactor/data/test_dict.npy', test_dict)

In [13]:
# load the test dictionary from disk
loaded_test_dict = np.load('/Users/dylanwells/popDMS/dylan_refactor/data/test_dict.npy', allow_pickle=True).item()  
print(loaded_test_dict)

{'a': 1, 'b': 2, 'c': 3}